using Godot;
using System.Collections.Generic;

namespace BloodDragon
{
    /// <summary>
    /// Lightweight localization: a key → text dictionary per locale, with
    /// fallback to Russian. All menu strings are routed through <see cref="T"/>
    /// so the ЯЗЫК ИНТЕРФЕЙСА setting actually changes the UI language.
    /// </summary>
    public static class Localization
    {
        private static readonly Dictionary<string, Dictionary<string, string>> Tables = new()
        {
            ["ru"] = new Dictionary<string, string>
            {
                ["menu.title"] = "BLOOD DRAGON 1.0",
                ["menu.press_any_key"] = "НАЖМИТЕ ЛЮБУЮ КЛАВИШУ",
                ["menu.campaign"] = "КАМПАНИЯ",
                ["menu.settings"] = "СПРАВКА И ПАРАМЕТРЫ",
                ["menu.quit"] = "ВЫЙТИ ИЗ ИГРЫ",
                ["menu.new_game"] = "НОВАЯ ИГРА",
                ["menu.continue"] = "ПРОДОЛЖИТЬ ИГРУ",
                ["menu.load_game"] = "ЗАГРУЗИТЬ ИГРУ",
                ["menu.back"] = "НАЗАД",
                ["menu.accept"] = "ПРИНЯТЬ",
                ["menu.settings_title"] = "СПРАВКА И ПАРАМЕТРЫ",
                ["menu.pause"] = "ПАУЗА",
                ["menu.resume"] = "ПРОДОЛЖИТЬ",
                ["menu.to_main_menu"] = "В ГЛАВНОЕ МЕНЮ",

                ["cat.display"] = "ИЗОБРАЖЕНИЕ",
                ["cat.calibration"] = "КАЛИБРОВКА",
                ["cat.video_quality"] = "КАЧЕСТВО ВИДЕО",
                ["cat.controls"] = "ЭЛЕМЕНТЫ УПРАВЛЕНИЯ",
                ["cat.gameplay"] = "ИГРОВОЙ ПРОЦЕСС",
                ["cat.language"] = "ЯЗЫК",
                ["cat.audio"] = "ЗВУК",
                ["cat.manual"] = "РУКОВОДСТВО",
                ["cat.credits"] = "ТИТРЫ",
                ["cat.stats"] = "МОНИТОРИНГ",

                ["set.show_stats"] = "ПОКАЗЫВАТЬ СТАТИСТИКУ",
                ["set.stats_mode"] = "РЕЖИМ СТАТИСТИКИ",
                ["set.stats_hint"] = "FPS, ВРЕМЯ КАДРА, DRAW CALLS, ПАМЯТЬ, УЗЛЫ — КОМПАКТНЫЙ / ПОДРОБНЫЙ ОВЕРЛЕЙ",

                ["val.stats_compact"] = "КОМПАКТНЫЙ",
                ["val.stats_full"] = "ПОДРОБНЫЙ",

                ["stats.fps"] = "FPS",
                ["stats.ms"] = "МС",
                ["stats.draw"] = "DRAW",
                ["stats.objects"] = "ОБЪЕКТЫ",
                ["stats.prims"] = "ТРЕУГОЛЬНИКИ",
                ["stats.video_mem"] = "ВИДЕОПАМЯТЬ",
                ["stats.buffer_mem"] = "БУФЕРЫ",
                ["stats.texture_mem"] = "ТЕКСТУРЫ",
                ["stats.nodes"] = "УЗЛЫ",
                ["stats.orphans"] = "СИРОТЫ",
                ["stats.shader_compiles"] = "КОМПИЛЯЦИИ ШЕЙДЕРОВ",
                ["stats.na"] = "Н/Д",

                ["set.resolution"] = "РАЗРЕШЕНИЕ ЭКРАНА",
                ["set.window_mode"] = "ОКОННЫЙ РЕЖИМ",
                ["set.windowed"] = "В ОКНЕ",
                ["set.fullscreen"] = "ПОЛНОЭКРАННЫЙ",
                ["set.vsync"] = "ВЕРТ. СИНХРОНИЗАЦИЯ",
                ["set.gpu_frames"] = "ФРЕЙМОВ В БУФЕРЕ GPU",
                ["set.letterbox"] = "FORMAT LETTERBOX",
                ["set.api"] = "ГРАФИЧЕСКИЙ API",
                ["set.directx"] = "DIRECTX",
                ["set.msaa"] = "MSAA СГЛАЖИВАНИЕ",
                ["set.a2c"] = "ALPHA TO COVERAGE",
                ["set.ssao"] = "МЕТОД SSAO",
                ["set.fov"] = "ПОЛЕ ЗРЕНИЯ",
                ["set.brightness"] = "ЯРКОСТЬ",
                ["set.contrast"] = "КОНТРАСТНОСТЬ",
                ["set.gamma"] = "GAMMA",
                ["set.overall_quality"] = "ОБЩЕЕ КАЧЕСТВО",
                ["set.texture_quality"] = "КАЧЕСТВО ТЕКСТУР",
                ["set.shadows"] = "ТЕНИ",
                ["set.shadow_quality"] = "КАЧЕСТВО ТЕНЕЙ",
                ["set.lighting"] = "ОСВЕЩЕНИЕ",
                ["set.post_processing"] = "ПОСТ-ОБРАБОТКА",
                ["set.water_quality"] = "КАЧЕСТВО ВОДЫ",
                ["set.draw_distance"] = "ДАЛЬНОСТЬ ПРОРИСОВКИ",
                ["set.mouse_sens"] = "ЧУВСТВИТЕЛЬНОСТЬ МЫШИ",
                ["set.invert_y"] = "ИНВЕРСИЯ МЫШИ ПО Y",
                ["set.controller_sens"] = "ЧУВСТВИТЕЛЬНОСТЬ КОНТРОЛЛЕРА",
                ["set.difficulty"] = "СЛОЖНОСТЬ",
                ["set.hints"] = "ПОДСКАЗКИ",
                ["set.auto_aim"] = "АВТОПРИЦЕЛИВАНИЕ",
                ["set.ui_language"] = "ЯЗЫК ИНТЕРФЕЙСА",
                ["set.voice_language"] = "ЯЗЫК ОЗВУЧКИ",
                ["set.subtitle_language"] = "ЯЗЫК СУБТИТРОВ",
                ["set.font"] = "ШРИФТ",
                ["set.master_volume"] = "ОБЩАЯ ГРОМКОСТЬ",
                ["set.music_volume"] = "ГРОМКОСТЬ МУЗЫКИ",
                ["set.sfx_volume"] = "ГРОМКОСТЬ ЭФФЕКТОВ",
                ["set.dialogue_volume"] = "ГРОМКОСТЬ ДИАЛОГОВ",
                ["set.ambient_volume"] = "ГРОМКОСТЬ ОКРУЖЕНИЯ",
                ["set.dynamic_range"] = "ДИНАМИЧЕСКИЙ ДИАПАЗОН",
                ["set.audio_output"] = "РЕЖИМ ВЫВОДА ЗВУКА",
                ["set.menu_voice"] = "ОЗВУЧКА МЕНЮ",
                ["set.fps_limit"] = "ЛИМИТ FPS",

                ["hint.resolution"] = "Размер картинки. Выше — резче, тяжелее для GPU",
                ["hint.window_mode"] = "Окно или на весь монитор",
                ["hint.vsync"] = "Убирает разрывы кадра, может добавить задержку ввода",
                ["hint.fps_limit"] = "Потолок кадров. 0 нагрузки меньше, отклик может стать мягче",
                ["hint.gpu_frames"] = "Сколько кадров GPU готовит заранее. Больше — плавнее, выше input lag",
                ["hint.letterbox"] = "Чёрные полосы, если соотношение сторон не совпадает",
                ["hint.api"] = "На Linux используется OpenGL Compatibility",
                ["hint.directx"] = "Графический API. DX9 — старые ПК, DX12 — новые",
                ["hint.msaa"] = "Сглаживает зубцы по краям. 4x — баланс, 8x дорого",
                ["hint.a2c"] = "Сглаживание прозрачных краёв листвы и сеток",
                ["hint.ssao"] = "Затемнение в щелях. HBAO+ красивее и тяжелее SSAO",
                ["hint.fov"] = "Шире обзор — больше периферии и искажений по краям",
                ["hint.brightness"] = "Общая яркость картинки",
                ["hint.contrast"] = "Разница между тёмным и светлым",
                ["hint.gamma"] = "Кривая средних тонов. Выше — светлее тени",
                ["hint.overall_quality"] = "Пресет сразу для текстур, теней и дальности",
                ["hint.texture_quality"] = "Чёткость поверхностей. Выше — больше видеопамяти",
                ["hint.shadows"] = "Включить тени. Выкл экономит кадры",
                ["hint.shadow_quality"] = "Резкость и дальность теней",
                ["hint.lighting"] = "Качество света и бликов",
                ["hint.post_processing"] = "Свечение, туман и цветокор. Красивее, дороже",
                ["hint.water_quality"] = "Отражения и волны на воде",
                ["hint.draw_distance"] = "Как далеко рисуются объекты",
                ["hint.mouse_sens"] = "Скорость камеры от мыши",
                ["hint.invert_y"] = "Движение мыши вверх опускает взгляд",
                ["hint.controller_sens"] = "Скорость камеры от стика",
                ["hint.rebind"] = "Enter — назначить клавишу. Esc — отмена",
                ["hint.difficulty"] = "Урон врагов и запас патронов",
                ["hint.hints"] = "Подсказки управления во время игры",
                ["hint.auto_aim"] = "Лёгкая помощь прицелу с геймпада",
                ["hint.ui_language"] = "Язык меню. Применится после Принять",
                ["hint.voice_language"] = "Язык озвучки персонажей",
                ["hint.subtitle_language"] = "Язык субтитров или выкл",
                ["hint.font"] = "Крупный и доступный — для чтения с дивана",
                ["hint.master_volume"] = "Общая громкость всего звука",
                ["hint.music_volume"] = "Громкость музыки",
                ["hint.sfx_volume"] = "Выстрелы, UI, удары",
                ["hint.dialogue_volume"] = "Речь персонажей",
                ["hint.ambient_volume"] = "Ветер, фон локации",
                ["hint.dynamic_range"] = "Высокий — кино, низкий — слышнее в шуме",
                ["hint.audio_output"] = "Стерео или объём. 5.1/7.1 нужен ресивер",
                ["hint.menu_voice"] = "Голосовые реплики в меню",
                ["hint.show_stats"] = "Оверлей FPS в углу экрана",
                ["hint.stats_mode"] = "Компакт — одна строка. Подробный — память и узлы",

                ["info.gpu_frames"] = "GPU заранее рисует несколько кадров, чтобы не простаивать. 2 — обычный выбор. 3–4 сглаживают просадки, но управление отвечает позже.",
                ["info.letterbox"] = "Если разрешение не совпадает с монитором, картинку вписывают в кадр с чёрными полями, без растягивания.",
                ["info.api"] = "Этот билд на Linux идёт через OpenGL 3.3 Compatibility. Vulkan в гостевой ВМ часто уходит в программный lavapipe.",
                ["info.directx"] = "DX12 быстрее на новом железе. DX11 — совместимость. DX9 отключает VSync и часть эффектов.",
                ["info.msaa"] = "MSAA сглаживает края геометрии, не весь кадр. 2x почти даром, 4x обычно достаточно, 8x заметно бьёт по FPS.",
                ["info.a2c"] = "Alpha to Coverage убирает ступенчатость на альфа-текстурах: листва, заборы, волосы. На Compatibility работает ограниченно.",
                ["info.ssao"] = "SSAO рисует грязь в углах из буфера глубины. HBAO+ точнее по нормалям и дороже. На слабом GPU лучше выкл.",
                ["info.fov"] = "Поле зрения камеры в градусах. 90 — привычный FPS. Выше 110 появляется «рыбий глаз» по краям экрана.",

                ["val.on"] = "ВКЛ",
                ["val.off"] = "ВЫКЛ",
                ["val.low"] = "НИЗКОЕ",
                ["val.medium"] = "СРЕДНЕЕ",
                ["val.high"] = "ВЫСОКОЕ",
                ["val.low_f"] = "НИЗКАЯ",
                ["val.medium_f"] = "СРЕДНЯЯ",
                ["val.high_f"] = "ВЫСОКАЯ",
                ["val.off_f"] = "ВЫКЛ",
                ["val.standard"] = "СТАНДАРТНОЕ",
                ["val.extended"] = "РАСШИРЕННОЕ",
                ["val.ssao"] = "SSAO",
                ["val.hbao"] = "HBAO+",
                ["val.easy"] = "ЛЁГКАЯ",
                ["val.normal"] = "НОРМАЛЬНАЯ",
                ["val.hard"] = "СЛОЖНАЯ",
                ["val.nightmare"] = "КОШМАР",
                ["val.stereo"] = "СТЕРЕО",
                ["val.surround51"] = "5.1",
                ["val.surround71"] = "7.1",
                ["val.low_dr"] = "НИЗКИЙ",
                ["val.medium_dr"] = "СРЕДНИЙ",
                ["val.high_dr"] = "ВЫСОКИЙ",
                ["val.standard_font"] = "СТАНДАРТНЫЙ",
                ["val.large_font"] = "КРУПНЫЙ",
                ["val.accessibility_font"] = "ДОСТУПНЫЙ",
                ["val.opengl"] = "OPENGL 3.3 COMPAT",
                ["val.dx9"] = "DIRECTX 9",
                ["val.dx11"] = "DIRECTX 11",
                ["val.dx12"] = "DIRECTX 12",
                ["val.off_sub"] = "ВЫКЛ",

                ["bind.move_forward"] = "ДВИЖЕНИЕ ВПЕРЁД",
                ["bind.move_backward"] = "ДВИЖЕНИЕ НАЗАД",
                ["bind.move_left"] = "ДВИЖЕНИЕ ВЛЕВО",
                ["bind.move_right"] = "ДВИЖЕНИЕ ВПРАВО",
                ["bind.jump"] = "ПРЫЖОК",
                ["bind.crouch"] = "ПРИСЕСТЬ",
                ["bind.sprint"] = "БЕГ",
                ["bind.shoot"] = "СТРЕЛЬБА",
                ["bind.aim"] = "ПРИЦЕЛИВАНИЕ",
                ["bind.reload"] = "ПЕРЕЗАРЯДКА",
                ["bind.interact"] = "ВЗАИМОДЕЙСТВИЕ",
                ["bind.inventory"] = "ИНВЕНТАРЬ",
                ["bind.map"] = "КАРТА",
                ["bind.pause"] = "ПАУЗА",

                ["game.hint"] = "WASD — движение   SHIFT — бег   CTRL — присесть   ПРОБЕЛ — прыжок   ESC — пауза",

                ["manual.controls"] = "УПРАВЛЕНИЕ",
                ["manual.controls_body"] = "WASD — движение, ПРОБЕЛ — прыжок, SHIFT — бег, CTRL — присесть\nЛКМ — стрельба, ПКМ — прицеливание, R — перезарядка, E — взаимодействие",
                ["manual.mechanics"] = "МЕХАНИКИ",
                ["manual.mechanics_body"] = "Исследуйте уровни, собирайте ресурсы и сражайтесь с драконами.\nИспользуйте укрытия и перезаряжайтесь вовремя.",
                ["manual.tips"] = "СОВЕТЫ",
                ["manual.tips_body"] = "• Цельтесь в слабые точки врага.\n• Сохраняйте патроны для сильных противников.\n• Изучите карту перед сражением.",

                ["credits.title"] = "BLOOD DRAGON",
                ["credits.version"] = "Версия: v1.0.0",
                ["credits.developer"] = "Разработчик: open-source",
                ["credits.engine"] = "Движок: Godot 4.8-dev4 .NET",
                ["credits.year"] = "Год выпуска: 2026",
                ["credits.licenses"] = "ЛИЦЕНЗИИ",
                ["credits.licenses_body"] = "Godot Engine (MIT)\nЭтот проект (MIT)",
                ["credits.contacts"] = "КОНТАКТЫ",
                ["credits.contacts_body"] = "Репозиторий на GitHub",
            },
            ["en"] = new Dictionary<string, string>
            {
                ["menu.title"] = "BLOOD DRAGON 1.0",
                ["menu.press_any_key"] = "PRESS ANY KEY",
                ["menu.campaign"] = "CAMPAIGN",
                ["menu.settings"] = "HELP & OPTIONS",
                ["menu.quit"] = "QUIT GAME",
                ["menu.new_game"] = "NEW GAME",
                ["menu.continue"] = "CONTINUE GAME",
                ["menu.load_game"] = "LOAD GAME",
                ["menu.back"] = "BACK",
                ["menu.accept"] = "ACCEPT",
                ["menu.settings_title"] = "HELP & OPTIONS",
                ["menu.pause"] = "PAUSED",
                ["menu.resume"] = "RESUME",
                ["menu.to_main_menu"] = "MAIN MENU",

                ["cat.display"] = "DISPLAY",
                ["cat.calibration"] = "CALIBRATION",
                ["cat.video_quality"] = "VIDEO QUALITY",
                ["cat.controls"] = "CONTROLS",
                ["cat.gameplay"] = "GAMEPLAY",
                ["cat.language"] = "LANGUAGE",
                ["cat.audio"] = "AUDIO",
                ["cat.manual"] = "MANUAL",
                ["cat.credits"] = "CREDITS",
                ["cat.stats"] = "MONITORING",

                ["set.show_stats"] = "SHOW STATISTICS",
                ["set.stats_mode"] = "STATS MODE",
                ["set.stats_hint"] = "FPS, FRAMETIME, DRAW CALLS, MEMORY, NODES — LIVE OVERLAY",

                ["val.stats_compact"] = "COMPACT",
                ["val.stats_full"] = "FULL",

                ["stats.fps"] = "FPS",
                ["stats.ms"] = "MS",
                ["stats.draw"] = "DRAW",
                ["stats.objects"] = "OBJECTS",
                ["stats.prims"] = "TRIS",
                ["stats.video_mem"] = "VRAM",
                ["stats.buffer_mem"] = "BUFFERS",
                ["stats.texture_mem"] = "TEXTURES",
                ["stats.nodes"] = "NODES",
                ["stats.orphans"] = "ORPHANS",
                ["stats.shader_compiles"] = "SHADER COMPILES",
                ["stats.na"] = "N/A",

                ["set.resolution"] = "SCREEN RESOLUTION",
                ["set.window_mode"] = "WINDOW MODE",
                ["set.windowed"] = "WINDOWED",
                ["set.fullscreen"] = "FULLSCREEN",
                ["set.vsync"] = "V-SYNC",
                ["set.gpu_frames"] = "GPU FRAMES IN FLIGHT",
                ["set.letterbox"] = "FORMAT LETTERBOX",
                ["set.api"] = "GRAPHICS API",
                ["set.directx"] = "DIRECTX",
                ["set.msaa"] = "MSAA",
                ["set.a2c"] = "ALPHA TO COVERAGE",
                ["set.ssao"] = "SSAO METHOD",
                ["set.fov"] = "FIELD OF VIEW",
                ["set.brightness"] = "BRIGHTNESS",
                ["set.contrast"] = "CONTRAST",
                ["set.gamma"] = "GAMMA",
                ["set.overall_quality"] = "OVERALL QUALITY",
                ["set.texture_quality"] = "TEXTURE QUALITY",
                ["set.shadows"] = "SHADOWS",
                ["set.shadow_quality"] = "SHADOW QUALITY",
                ["set.lighting"] = "LIGHTING",
                ["set.post_processing"] = "POST-PROCESSING",
                ["set.water_quality"] = "WATER QUALITY",
                ["set.draw_distance"] = "DRAW DISTANCE",
                ["set.mouse_sens"] = "MOUSE SENSITIVITY",
                ["set.invert_y"] = "INVERT MOUSE Y",
                ["set.controller_sens"] = "CONTROLLER SENSITIVITY",
                ["set.difficulty"] = "DIFFICULTY",
                ["set.hints"] = "HINTS",
                ["set.auto_aim"] = "AUTO-AIM",
                ["set.ui_language"] = "UI LANGUAGE",
                ["set.voice_language"] = "VOICE LANGUAGE",
                ["set.subtitle_language"] = "SUBTITLE LANGUAGE",
                ["set.font"] = "FONT",
                ["set.master_volume"] = "MASTER VOLUME",
                ["set.music_volume"] = "MUSIC VOLUME",
                ["set.sfx_volume"] = "SFX VOLUME",
                ["set.dialogue_volume"] = "DIALOGUE VOLUME",
                ["set.ambient_volume"] = "AMBIENT VOLUME",
                ["set.dynamic_range"] = "DYNAMIC RANGE",
                ["set.audio_output"] = "AUDIO OUTPUT",
                ["set.menu_voice"] = "MENU VOICE",
                ["set.fps_limit"] = "FPS LIMIT",

                ["hint.resolution"] = "Output size. Higher is sharper and heavier on the GPU",
                ["hint.window_mode"] = "Windowed or fill the monitor",
                ["hint.vsync"] = "Stops screen tearing; can add input latency",
                ["hint.fps_limit"] = "Cap on frame rate. Lower cap eases the GPU",
                ["hint.gpu_frames"] = "Frames the GPU prepares ahead. More = smoother, more lag",
                ["hint.letterbox"] = "Black bars when the aspect ratio does not match",
                ["hint.api"] = "Linux builds use OpenGL Compatibility",
                ["hint.directx"] = "Graphics API. DX9 for old PCs, DX12 for new ones",
                ["hint.msaa"] = "Smooths jagged edges. 4x is the usual balance",
                ["hint.a2c"] = "Smooths cutout edges on foliage and fences",
                ["hint.ssao"] = "Darkens crevices. HBAO+ looks better and costs more",
                ["hint.fov"] = "Wider view, more peripheral distortion",
                ["hint.brightness"] = "Overall picture brightness",
                ["hint.contrast"] = "Gap between dark and light",
                ["hint.gamma"] = "Midtone curve. Higher lifts shadows",
                ["hint.overall_quality"] = "Preset for textures, shadows and distance",
                ["hint.texture_quality"] = "Surface sharpness. Higher uses more VRAM",
                ["hint.shadows"] = "Toggle shadows. Off saves frames",
                ["hint.shadow_quality"] = "Shadow sharpness and range",
                ["hint.lighting"] = "Light and specular quality",
                ["hint.post_processing"] = "Glow, fog and color. Prettier, costlier",
                ["hint.water_quality"] = "Reflections and waves",
                ["hint.draw_distance"] = "How far objects are drawn",
                ["hint.mouse_sens"] = "Camera speed from the mouse",
                ["hint.invert_y"] = "Push mouse up to look down",
                ["hint.controller_sens"] = "Camera speed from the stick",
                ["hint.rebind"] = "Enter to bind a key. Esc cancels",
                ["hint.difficulty"] = "Enemy damage and ammo supply",
                ["hint.hints"] = "On-screen control tips in-game",
                ["hint.auto_aim"] = "Mild aim assist on a gamepad",
                ["hint.ui_language"] = "Menu language. Applies after Accept",
                ["hint.voice_language"] = "Spoken character language",
                ["hint.subtitle_language"] = "Subtitle language, or off",
                ["hint.font"] = "Large / accessible for sofa viewing",
                ["hint.master_volume"] = "Overall volume",
                ["hint.music_volume"] = "Music volume",
                ["hint.sfx_volume"] = "Guns, UI, impacts",
                ["hint.dialogue_volume"] = "Character speech",
                ["hint.ambient_volume"] = "Wind and room tone",
                ["hint.dynamic_range"] = "High is cinematic; low is louder in noise",
                ["hint.audio_output"] = "Stereo or surround. 5.1/7.1 needs a receiver",
                ["hint.menu_voice"] = "Spoken lines in menus",
                ["hint.show_stats"] = "FPS overlay in the corner",
                ["hint.stats_mode"] = "Compact is one line. Full adds memory and nodes",

                ["info.gpu_frames"] = "The GPU queues extra frames so it never idles. 2 is typical. 3–4 hide stutters but the controls answer later.",
                ["info.letterbox"] = "When the resolution aspect does not match the monitor, the image is fitted with black bars instead of stretching.",
                ["info.api"] = "This Linux build uses OpenGL 3.3 Compatibility. Vulkan in a guest VM often falls back to software lavapipe.",
                ["info.directx"] = "DX12 is faster on new hardware. DX11 is the compatibility pick. DX9 disables VSync and some effects.",
                ["info.msaa"] = "MSAA smooths geometry edges, not the whole frame. 2x is cheap, 4x is enough, 8x hits FPS hard.",
                ["info.a2c"] = "Alpha to Coverage cleans stair-steps on alpha cutouts: leaves, fences, hair. Limited on Compatibility.",
                ["info.ssao"] = "SSAO dirties corners from the depth buffer. HBAO+ uses normals and costs more. Turn off on a weak GPU.",
                ["info.fov"] = "Camera field of view in degrees. 90 is a typical FPS. Past 110 the sides fish-eye.",

                ["val.on"] = "ON",
                ["val.off"] = "OFF",
                ["val.low"] = "LOW",
                ["val.medium"] = "MEDIUM",
                ["val.high"] = "HIGH",
                ["val.low_f"] = "LOW",
                ["val.medium_f"] = "MEDIUM",
                ["val.high_f"] = "HIGH",
                ["val.off_f"] = "OFF",
                ["val.standard"] = "STANDARD",
                ["val.extended"] = "EXTENDED",
                ["val.ssao"] = "SSAO",
                ["val.hbao"] = "HBAO+",
                ["val.easy"] = "EASY",
                ["val.normal"] = "NORMAL",
                ["val.hard"] = "HARD",
                ["val.nightmare"] = "NIGHTMARE",
                ["val.stereo"] = "STEREO",
                ["val.surround51"] = "5.1",
                ["val.surround71"] = "7.1",
                ["val.low_dr"] = "LOW",
                ["val.medium_dr"] = "MEDIUM",
                ["val.high_dr"] = "HIGH",
                ["val.standard_font"] = "STANDARD",
                ["val.large_font"] = "LARGE",
                ["val.accessibility_font"] = "ACCESSIBILITY",
                ["val.opengl"] = "OPENGL 3.3 COMPAT",
                ["val.dx9"] = "DIRECTX 9",
                ["val.dx11"] = "DIRECTX 11",
                ["val.dx12"] = "DIRECTX 12",
                ["val.off_sub"] = "OFF",

                ["bind.move_forward"] = "MOVE FORWARD",
                ["bind.move_backward"] = "MOVE BACKWARD",
                ["bind.move_left"] = "MOVE LEFT",
                ["bind.move_right"] = "MOVE RIGHT",
                ["bind.jump"] = "JUMP",
                ["bind.crouch"] = "CROUCH",
                ["bind.sprint"] = "SPRINT",
                ["bind.shoot"] = "SHOOT",
                ["bind.aim"] = "AIM",
                ["bind.reload"] = "RELOAD",
                ["bind.interact"] = "INTERACT",
                ["bind.inventory"] = "INVENTORY",
                ["bind.map"] = "MAP",
                ["bind.pause"] = "PAUSE",

                ["game.hint"] = "WASD — move   SHIFT — sprint   CTRL — crouch   SPACE — jump   ESC — pause",

                ["manual.controls"] = "CONTROLS",
                ["manual.controls_body"] = "WASD — move, SPACE — jump, SHIFT — sprint, CTRL — crouch\nLMB — shoot, RMB — aim, R — reload, E — interact",
                ["manual.mechanics"] = "MECHANICS",
                ["manual.mechanics_body"] = "Explore levels, gather resources and fight dragons.\nUse cover and reload in time.",
                ["manual.tips"] = "TIPS",
                ["manual.tips_body"] = "• Aim for weak spots.\n• Save ammo for strong enemies.\n• Study the map before fighting.",

                ["credits.title"] = "BLOOD DRAGON",
                ["credits.version"] = "Version: v1.0.0",
                ["credits.developer"] = "Developer: open-source",
                ["credits.engine"] = "Engine: Godot 4.8-dev4 .NET",
                ["credits.year"] = "Year: 2026",
                ["credits.licenses"] = "LICENSES",
                ["credits.licenses_body"] = "Godot Engine (MIT)\nThis project (MIT)",
                ["credits.contacts"] = "CONTACTS",
                ["credits.contacts_body"] = "GitHub repository",
            },
        };

        /// <summary>Current locale from the live settings, falling back to "ru".</summary>
        public static string CurrentLocale
        {
            get
            {
                var s = SettingsManager.Instance?.Current;
                if (s == null) return "ru";
                string loc = s.UiLanguage;
                return Tables.ContainsKey(loc) ? loc : "ru";
            }
        }

        /// <summary>Translate a key; falls back to Russian, then to the key itself.</summary>
        public static string T(string key)
        {
            string loc = CurrentLocale;
            if (Tables[loc].TryGetValue(key, out var v)) return v;
            if (Tables["ru"].TryGetValue(key, out v)) return v;
            return key;
        }

        public static bool Has(string key)
        {
            if (string.IsNullOrEmpty(key)) return false;
            string loc = CurrentLocale;
            return Tables[loc].ContainsKey(key) || Tables["ru"].ContainsKey(key);
        }
    }
}
