using Godot;
using System.Collections.Generic;

namespace BloodDragon
{
    /// <summary>
    /// Lightweight localization: a key → text dictionary per locale, with
    /// fallback to Russian. All menu strings are routed through <see cref="T"/>
    /// so the ЯЗЫК ИНТЕРФЕЙСА setting actually changes the UI language.
    /// </summary>
    public static class Localization
    {
        private static readonly Dictionary<string, Dictionary<string, string>> Tables = new()
        {
            ["ru"] = new Dictionary<string, string>
            {
                ["menu.title"] = "BLOOD DRAGON 1.0",
                ["menu.press_any_key"] = "НАЖМИТЕ ЛЮБУЮ КЛАВИШУ",
                ["menu.campaign"] = "КАМПАНИЯ",
                ["menu.settings"] = "СПРАВКА И ПАРАМЕТРЫ",
                ["menu.quit"] = "ВЫЙТИ ИЗ ИГРЫ",
                ["menu.new_game"] = "НОВАЯ ИГРА",
                ["menu.continue"] = "ПРОДОЛЖИТЬ ИГРУ",
                ["menu.load_game"] = "ЗАГРУЗИТЬ ИГРУ",
                ["menu.back"] = "НАЗАД",
                ["menu.accept"] = "ПРИНЯТЬ",
                ["menu.settings_title"] = "СПРАВКА И ПАРАМЕТРЫ",
                ["menu.pause"] = "ПАУЗА",
                ["menu.resume"] = "ПРОДОЛЖИТЬ",
                ["menu.to_main_menu"] = "В ГЛАВНОЕ МЕНЮ",

                ["cat.display"] = "ИЗОБРАЖЕНИЕ",
                ["cat.calibration"] = "КАЛИБРОВКА",
                ["cat.video_quality"] = "КАЧЕСТВО ВИДЕО",
                ["cat.controls"] = "ЭЛЕМЕНТЫ УПРАВЛЕНИЯ",
                ["cat.gameplay"] = "ИГРОВОЙ ПРОЦЕСС",
                ["cat.language"] = "ЯЗЫК",
                ["cat.audio"] = "ЗВУК",
                ["cat.manual"] = "РУКОВОДСТВО",
                ["cat.credits"] = "ТИТРЫ",
                ["cat.stats"] = "МОНИТОРИНГ",

                ["set.show_stats"] = "ПОКАЗЫВАТЬ СТАТИСТИКУ",
                ["set.stats_mode"] = "РЕЖИМ СТАТИСТИКИ",
                ["set.stats_hint"] = "FPS, ВРЕМЯ КАДРА, ПАМЯТЬ, ДРАВЕРЫ, УЗЛЫ — ОВЕРЛЕЙ ПОВЕРХ ИГРЫ",

                ["val.stats_compact"] = "КОМПАКТНЫЙ",
                ["val.stats_full"] = "ПОДРОБНЫЙ",

                ["stats.fps"] = "FPS",
                ["stats.ms"] = "МС",
                ["stats.draw"] = "ДРАВЕРЫ",
                ["stats.objects"] = "ОБЪЕКТЫ",
                ["stats.prims"] = "ТРЕУГЛЬНИКИ",
                ["stats.video_mem"] = "ВИДЕОПАМЯТЬ",
                ["stats.buffer_mem"] = "БУФЕРЫ",
                ["stats.texture_mem"] = "ТЕКСТУРЫ",
                ["stats.nodes"] = "УЗЛЫ",
                ["stats.orphans"] = "ОСАМЫ",
                ["stats.shader_compiles"] = "КОМПИЛЯЦИИ ШЕЙДЕРОВ",
                ["stats.na"] = "Н/Д",

                ["set.resolution"] = "РАЗРЕШЕНИЕ ЭКРАНА",
                ["set.window_mode"] = "ОКОННЫЙ РЕЖИМ",
                ["set.windowed"] = "В ОКНЕ",
                ["set.fullscreen"] = "ПОЛНОЭКРАННЫЙ",
                ["set.vsync"] = "ВЕРТ. СИНХРОНИЗАЦИЯ",
                ["set.gpu_frames"] = "ФРЕЙМОВ В БУФЕРЕ GPU",
                ["set.letterbox"] = "FORMAT LETTERBOX",
                ["set.api"] = "ГРАФИЧЕСКИЙ API",
                ["set.directx"] = "DIRECTX",
                ["set.msaa"] = "MSAA СГЛАЖИВАНИЕ",
                ["set.a2c"] = "ALPHA TO COVERAGE",
                ["set.ssao"] = "МЕТОД SSAO",
                ["set.fov"] = "ПОЛЕ ЗРЕНИЯ",
                ["set.brightness"] = "ЯРКОСТЬ",
                ["set.contrast"] = "КОНТРАСТНОСТЬ",
                ["set.gamma"] = "GAMMA",
                ["set.overall_quality"] = "ОБЩЕЕ КАЧЕСТВО",
                ["set.texture_quality"] = "КАЧЕСТВО ТЕКСТУР",
                ["set.shadows"] = "ТЕНИ",
                ["set.shadow_quality"] = "КАЧЕСТВО ТЕНЕЙ",
                ["set.lighting"] = "ОСВЕЩЕНИЕ",
                ["set.post_processing"] = "ПОСТ-ОБРАБОТКА",
                ["set.water_quality"] = "КАЧЕСТВО ВОДЫ",
                ["set.draw_distance"] = "ДАЛЬНОСТЬ ПРОРИСОВКИ",
                ["set.mouse_sens"] = "ЧУВСТВИТЕЛЬНОСТЬ МЫШИ",
                ["set.invert_y"] = "ИНВЕРСИЯ МЫШИ ПО Y",
                ["set.controller_sens"] = "ЧУВСТВИТЕЛЬНОСТЬ КОНТРОЛЛЕРА",
                ["set.difficulty"] = "СЛОЖНОСТЬ",
                ["set.hints"] = "ПОДСКАЗКИ",
                ["set.auto_aim"] = "АВТОПРИЦЕЛИВАНИЕ",
                ["set.ui_language"] = "ЯЗЫК ИНТЕРФЕЙСА",
                ["set.voice_language"] = "ЯЗЫК ОЗВУЧКИ",
                ["set.subtitle_language"] = "ЯЗЫК СУБТИТРОВ",
                ["set.font"] = "ШРИФТ",
                ["set.master_volume"] = "ОБЩАЯ ГРОМКОСТЬ",
                ["set.music_volume"] = "ГРОМКОСТЬ МУЗЫКИ",
                ["set.sfx_volume"] = "ГРОМКОСТЬ ЭФФЕКТОВ",
                ["set.dialogue_volume"] = "ГРОМКОСТЬ ДИАЛОГОВ",
                ["set.ambient_volume"] = "ГРОМКОСТЬ ОКРУЖЕНИЯ",
                ["set.dynamic_range"] = "ДИНАМИЧЕСКИЙ ДИАПАЗОН",
                ["set.audio_output"] = "РЕЖИМ ВЫВОДА ЗВУКА",
                ["set.menu_voice"] = "ОЗВУЧКА МЕНЮ",
                ["set.fps_limit"] = "ЛИМИТ FPS",

                ["val.on"] = "ВКЛ",
                ["val.off"] = "ВЫКЛ",
                ["val.low"] = "НИЗКОЕ",
                ["val.medium"] = "СРЕДНЕЕ",
                ["val.high"] = "ВЫСОКОЕ",
                ["val.low_f"] = "НИЗКАЯ",
                ["val.medium_f"] = "СРЕДНЯЯ",
                ["val.high_f"] = "ВЫСОКАЯ",
                ["val.off_f"] = "ВЫКЛ",
                ["val.standard"] = "СТАНДАРТНОЕ",
                ["val.extended"] = "РАСШИРЕННОЕ",
                ["val.ssao"] = "SSAO",
                ["val.hbao"] = "HBAO+",
                ["val.easy"] = "ЛЁГКАЯ",
                ["val.normal"] = "НОРМАЛЬНАЯ",
                ["val.hard"] = "СЛОЖНАЯ",
                ["val.nightmare"] = "КОШМАР",
                ["val.stereo"] = "СТЕРЕО",
                ["val.surround51"] = "5.1",
                ["val.surround71"] = "7.1",
                ["val.low_dr"] = "НИЗКИЙ",
                ["val.medium_dr"] = "СРЕДНИЙ",
                ["val.high_dr"] = "ВЫСОКИЙ",
                ["val.standard_font"] = "СТАНДАРТНЫЙ",
                ["val.large_font"] = "КРУПНЫЙ",
                ["val.accessibility_font"] = "ДОСТУПНЫЙ",
                ["val.opengl"] = "OPENGL 3.3 COMPAT",
                ["val.dx9"] = "DIRECTX 9",
                ["val.dx11"] = "DIRECTX 11",
                ["val.dx12"] = "DIRECTX 12",
                ["val.off_sub"] = "ВЫКЛ",

                ["bind.move_forward"] = "ДВИЖЕНИЕ ВПЕРЁД",
                ["bind.move_backward"] = "ДВИЖЕНИЕ НАЗАД",
                ["bind.move_left"] = "ДВИЖЕНИЕ ВЛЕВО",
                ["bind.move_right"] = "ДВИЖЕНИЕ ВПРАВО",
                ["bind.jump"] = "ПРЫЖОК",
                ["bind.crouch"] = "ПРИСЕСТЬ",
                ["bind.sprint"] = "БЕГ",
                ["bind.shoot"] = "СТРЕЛЬБА",
                ["bind.aim"] = "ПРИЦЕЛИВАНИЕ",
                ["bind.reload"] = "ПЕРЕЗАРЯДКА",
                ["bind.interact"] = "ВЗАИМОДЕЙСТВИЕ",
                ["bind.inventory"] = "ИНВЕНТАРЬ",
                ["bind.map"] = "КАРТА",
                ["bind.pause"] = "ПАУЗА",

                ["game.hint"] = "WASD — движение   SHIFT — бег   CTRL — присесть   ПРОБЕЛ — прыжок   ESC — пауза",

                ["manual.controls"] = "УПРАВЛЕНИЕ",
                ["manual.controls_body"] = "WASD — движение, ПРОБЕЛ — прыжок, SHIFT — бег, CTRL — присесть\nЛКМ — стрельба, ПКМ — прицеливание, R — перезарядка, E — взаимодействие",
                ["manual.mechanics"] = "МЕХАНИКИ",
                ["manual.mechanics_body"] = "Исследуйте уровни, собирайте ресурсы и сражайтесь с драконами.\nИспользуйте укрытия и перезаряжайтесь вовремя.",
                ["manual.tips"] = "СОВЕТЫ",
                ["manual.tips_body"] = "• Цельтесь в слабые точки врага.\n• Сохраняйте патроны для сильных противников.\n• Изучите карту перед сражением.",

                ["credits.title"] = "BLOOD DRAGON",
                ["credits.version"] = "Версия: v1.0.0",
                ["credits.developer"] = "Разработчик: open-source",
                ["credits.engine"] = "Движок: Godot 4.8-dev4 .NET",
                ["credits.year"] = "Год выпуска: 2026",
                ["credits.licenses"] = "ЛИЦЕНЗИИ",
                ["credits.licenses_body"] = "Godot Engine (MIT)\nЭтот проект (MIT)",
                ["credits.contacts"] = "КОНТАКТЫ",
                ["credits.contacts_body"] = "Репозиторий на GitHub",
            },
            ["en"] = new Dictionary<string, string>
            {
                ["menu.title"] = "BLOOD DRAGON 1.0",
                ["menu.press_any_key"] = "PRESS ANY KEY",
                ["menu.campaign"] = "CAMPAIGN",
                ["menu.settings"] = "HELP & OPTIONS",
                ["menu.quit"] = "QUIT GAME",
                ["menu.new_game"] = "NEW GAME",
                ["menu.continue"] = "CONTINUE GAME",
                ["menu.load_game"] = "LOAD GAME",
                ["menu.back"] = "BACK",
                ["menu.accept"] = "ACCEPT",
                ["menu.settings_title"] = "HELP & OPTIONS",
                ["menu.pause"] = "PAUSED",
                ["menu.resume"] = "RESUME",
                ["menu.to_main_menu"] = "MAIN MENU",

                ["cat.display"] = "DISPLAY",
                ["cat.calibration"] = "CALIBRATION",
                ["cat.video_quality"] = "VIDEO QUALITY",
                ["cat.controls"] = "CONTROLS",
                ["cat.gameplay"] = "GAMEPLAY",
                ["cat.language"] = "LANGUAGE",
                ["cat.audio"] = "AUDIO",
                ["cat.manual"] = "MANUAL",
                ["cat.credits"] = "CREDITS",
                ["cat.stats"] = "MONITORING",

                ["set.show_stats"] = "SHOW STATISTICS",
                ["set.stats_mode"] = "STATS MODE",
                ["set.stats_hint"] = "FPS, FRAMETIME, DRAW CALLS, MEMORY, NODES — LIVE OVERLAY",

                ["val.stats_compact"] = "COMPACT",
                ["val.stats_full"] = "FULL",

                ["stats.fps"] = "FPS",
                ["stats.ms"] = "MS",
                ["stats.draw"] = "DRAW",
                ["stats.objects"] = "OBJECTS",
                ["stats.prims"] = "TRIS",
                ["stats.video_mem"] = "VRAM",
                ["stats.buffer_mem"] = "BUFFERS",
                ["stats.texture_mem"] = "TEXTURES",
                ["stats.nodes"] = "NODES",
                ["stats.orphans"] = "ORPHANS",
                ["stats.shader_compiles"] = "SHADER COMPILES",
                ["stats.na"] = "N/A",

                ["set.resolution"] = "SCREEN RESOLUTION",
                ["set.window_mode"] = "WINDOW MODE",
                ["set.windowed"] = "WINDOWED",
                ["set.fullscreen"] = "FULLSCREEN",
                ["set.vsync"] = "V-SYNC",
                ["set.gpu_frames"] = "GPU FRAMES IN FLIGHT",
                ["set.letterbox"] = "FORMAT LETTERBOX",
                ["set.api"] = "GRAPHICS API",
                ["set.directx"] = "DIRECTX",
                ["set.msaa"] = "MSAA",
                ["set.a2c"] = "ALPHA TO COVERAGE",
                ["set.ssao"] = "SSAO METHOD",
                ["set.fov"] = "FIELD OF VIEW",
                ["set.brightness"] = "BRIGHTNESS",
                ["set.contrast"] = "CONTRAST",
                ["set.gamma"] = "GAMMA",
                ["set.overall_quality"] = "OVERALL QUALITY",
                ["set.texture_quality"] = "TEXTURE QUALITY",
                ["set.shadows"] = "SHADOWS",
                ["set.shadow_quality"] = "SHADOW QUALITY",
                ["set.lighting"] = "LIGHTING",
                ["set.post_processing"] = "POST-PROCESSING",
                ["set.water_quality"] = "WATER QUALITY",
                ["set.draw_distance"] = "DRAW DISTANCE",
                ["set.mouse_sens"] = "MOUSE SENSITIVITY",
                ["set.invert_y"] = "INVERT MOUSE Y",
                ["set.controller_sens"] = "CONTROLLER SENSITIVITY",
                ["set.difficulty"] = "DIFFICULTY",
                ["set.hints"] = "HINTS",
                ["set.auto_aim"] = "AUTO-AIM",
                ["set.ui_language"] = "UI LANGUAGE",
                ["set.voice_language"] = "VOICE LANGUAGE",
                ["set.subtitle_language"] = "SUBTITLE LANGUAGE",
                ["set.font"] = "FONT",
                ["set.master_volume"] = "MASTER VOLUME",
                ["set.music_volume"] = "MUSIC VOLUME",
                ["set.sfx_volume"] = "SFX VOLUME",
                ["set.dialogue_volume"] = "DIALOGUE VOLUME",
                ["set.ambient_volume"] = "AMBIENT VOLUME",
                ["set.dynamic_range"] = "DYNAMIC RANGE",
                ["set.audio_output"] = "AUDIO OUTPUT",
                ["set.menu_voice"] = "MENU VOICE",
                ["set.fps_limit"] = "FPS LIMIT",

                ["val.on"] = "ON",
                ["val.off"] = "OFF",
                ["val.low"] = "LOW",
                ["val.medium"] = "MEDIUM",
                ["val.high"] = "HIGH",
                ["val.low_f"] = "LOW",
                ["val.medium_f"] = "MEDIUM",
                ["val.high_f"] = "HIGH",
                ["val.off_f"] = "OFF",
                ["val.standard"] = "STANDARD",
                ["val.extended"] = "EXTENDED",
                ["val.ssao"] = "SSAO",
                ["val.hbao"] = "HBAO+",
                ["val.easy"] = "EASY",
                ["val.normal"] = "NORMAL",
                ["val.hard"] = "HARD",
                ["val.nightmare"] = "NIGHTMARE",
                ["val.stereo"] = "STEREO",
                ["val.surround51"] = "5.1",
                ["val.surround71"] = "7.1",
                ["val.low_dr"] = "LOW",
                ["val.medium_dr"] = "MEDIUM",
                ["val.high_dr"] = "HIGH",
                ["val.standard_font"] = "STANDARD",
                ["val.large_font"] = "LARGE",
                ["val.accessibility_font"] = "ACCESSIBILITY",
                ["val.opengl"] = "OPENGL 3.3 COMPAT",
                ["val.dx9"] = "DIRECTX 9",
                ["val.dx11"] = "DIRECTX 11",
                ["val.dx12"] = "DIRECTX 12",
                ["val.off_sub"] = "OFF",

                ["bind.move_forward"] = "MOVE FORWARD",
                ["bind.move_backward"] = "MOVE BACKWARD",
                ["bind.move_left"] = "MOVE LEFT",
                ["bind.move_right"] = "MOVE RIGHT",
                ["bind.jump"] = "JUMP",
                ["bind.crouch"] = "CROUCH",
                ["bind.sprint"] = "SPRINT",
                ["bind.shoot"] = "SHOOT",
                ["bind.aim"] = "AIM",
                ["bind.reload"] = "RELOAD",
                ["bind.interact"] = "INTERACT",
                ["bind.inventory"] = "INVENTORY",
                ["bind.map"] = "MAP",
                ["bind.pause"] = "PAUSE",

                ["game.hint"] = "WASD — move   SHIFT — sprint   CTRL — crouch   SPACE — jump   ESC — pause",

                ["manual.controls"] = "CONTROLS",
                ["manual.controls_body"] = "WASD — move, SPACE — jump, SHIFT — sprint, CTRL — crouch\nLMB — shoot, RMB — aim, R — reload, E — interact",
                ["manual.mechanics"] = "MECHANICS",
                ["manual.mechanics_body"] = "Explore levels, gather resources and fight dragons.\nUse cover and reload in time.",
                ["manual.tips"] = "TIPS",
                ["manual.tips_body"] = "• Aim for weak spots.\n• Save ammo for strong enemies.\n• Study the map before fighting.",

                ["credits.title"] = "BLOOD DRAGON",
                ["credits.version"] = "Version: v1.0.0",
                ["credits.developer"] = "Developer: open-source",
                ["credits.engine"] = "Engine: Godot 4.8-dev4 .NET",
                ["credits.year"] = "Year: 2026",
                ["credits.licenses"] = "LICENSES",
                ["credits.licenses_body"] = "Godot Engine (MIT)\nThis project (MIT)",
                ["credits.contacts"] = "CONTACTS",
                ["credits.contacts_body"] = "GitHub repository",
            },
        };

        /// <summary>Current locale from the live settings, falling back to "ru".</summary>
        public static string CurrentLocale
        {
            get
            {
                var s = SettingsManager.Instance?.Current;
                if (s == null) return "ru";
                string loc = s.UiLanguage;
                return Tables.ContainsKey(loc) ? loc : "ru";
            }
        }

        /// <summary>Translate a key; falls back to Russian, then to the key itself.</summary>
        public static string T(string key)
        {
            string loc = CurrentLocale;
            if (Tables[loc].TryGetValue(key, out var v)) return v;
            if (Tables["ru"].TryGetValue(key, out v)) return v;
            return key;
        }
    }
}
